services:
  web:
    build: .
    container_name: fastapi_service
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGO_URI}
    env_file:
      - .env
    image: rizkialhamid/cs160-project-backend:latest
